# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Use firebase app distribution to deployment'
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  lane :android_beta_app do
    firebase_app_distribution(
      app: '1:500472135511:android:9678b0763fff9a023f4812',
      testers: 'tintm.dev@gmail.com',
      release_notes: 'Release Hello Flutter app',
      firebase_cli_path: '/usr/local/bin/firebase',
      apk_path: '../build/app/outputs/apk/release/app-release.apk'
    )
  end
end
